services:
  - type: web
    name: queue-system
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 3457
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SMS_SECRET_ID
        sync: false
      - key: SMS_SECRET_KEY
        sync: false
      - key: SMS_SDK_APP_ID
        sync: false
      - key: SMS_SIGN_NAME
        value: 湘阁里辣
      - key: SMS_TEMPLATE_ID
        sync: false
      - key: WECOM_WEBHOOK_URL
        value: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=d35ec9fd-b3e2-4132-848c-0fbc7ab38107
